local M = {}

local function merge(base, extra)
  return vim.tbl_extend("force", base, extra or {})
end

local function link(group)
  return { link = group }
end

function M.get(colors, opts)
  local transparent = opts.transparent
  local dim_inactive = opts.dim_inactive
  local styles = opts.styles or {}

  local bg = transparent and colors.none or colors.bg
  local bg_alt = transparent and colors.none or colors.panel
  local bg_float = transparent and colors.none or colors.bg_float
  local bg_status = transparent and colors.none or colors.statusline
  local inactive_bg = dim_inactive and colors.panel or bg

  return {
    ColorColumn = { bg = colors.cursorline },
    Conceal = { fg = colors.comment },
    CurSearch = { fg = colors.fg, bg = colors.search_current },
    Cursor = { fg = colors.bg, bg = colors.cursor },
    CursorColumn = { bg = colors.cursorline },
    CursorIM = { fg = colors.bg, bg = colors.cursor },
    CursorLine = { bg = colors.cursorline },
    CursorLineNr = { fg = colors.yellow, bold = true },
    DiagnosticDeprecated = { fg = colors.comment, strikethrough = true },
    DiagnosticError = { fg = colors.diag.error },
    DiagnosticFloatingError = { fg = colors.diag.error, bg = bg_float },
    DiagnosticFloatingHint = { fg = colors.diag.hint, bg = bg_float },
    DiagnosticFloatingInfo = { fg = colors.diag.info, bg = bg_float },
    DiagnosticFloatingOk = { fg = colors.diag.ok, bg = bg_float },
    DiagnosticFloatingWarn = { fg = colors.diag.warn, bg = bg_float },
    DiagnosticHint = { fg = colors.diag.hint },
    DiagnosticInfo = { fg = colors.diag.info },
    DiagnosticOk = { fg = colors.diag.ok },
    DiagnosticSignError = { fg = colors.diag.error, bg = bg },
    DiagnosticSignHint = { fg = colors.diag.hint, bg = bg },
    DiagnosticSignInfo = { fg = colors.diag.info, bg = bg },
    DiagnosticSignOk = { fg = colors.diag.ok, bg = bg },
    DiagnosticSignWarn = { fg = colors.diag.warn, bg = bg },
    DiagnosticUnderlineError = { sp = colors.diag.error, undercurl = true },
    DiagnosticUnderlineHint = { sp = colors.diag.hint, undercurl = true },
    DiagnosticUnderlineInfo = { sp = colors.diag.info, undercurl = true },
    DiagnosticUnderlineOk = { sp = colors.diag.ok, undercurl = true },
    DiagnosticUnderlineWarn = { sp = colors.diag.warn, undercurl = true },
    DiagnosticUnnecessary = { fg = colors.comment, italic = true },
    DiagnosticVirtualTextError = { fg = colors.diag.error, bg = colors.diag_bg.error },
    DiagnosticVirtualTextHint = { fg = colors.diag.hint, bg = colors.diag_bg.hint },
    DiagnosticVirtualTextInfo = { fg = colors.diag.info, bg = colors.diag_bg.info },
    DiagnosticVirtualTextOk = { fg = colors.diag.ok, bg = colors.diag_bg.ok },
    DiagnosticVirtualTextWarn = { fg = colors.diag.warn, bg = colors.diag_bg.warn },
    DiagnosticWarn = { fg = colors.diag.warn },
    DiffAdd = { bg = colors.git_bg.add, fg = colors.git.add },
    DiffChange = { bg = colors.git_bg.change, fg = colors.git.change },
    DiffDelete = { bg = colors.git_bg.delete, fg = colors.git.delete },
    DiffText = { bg = colors.selection_soft, fg = colors.yellow },
    Directory = { fg = colors.blue },
    EndOfBuffer = { fg = colors.bg },
    ErrorMsg = { fg = colors.red },
    FloatBorder = { fg = colors.border, bg = bg_float },
    FloatTitle = { fg = colors.blue, bg = bg_float },
    FoldColumn = { fg = colors.comment, bg = bg },
    Folded = { fg = colors.comment, bg = bg_alt, italic = true },
    IncSearch = { fg = colors.fg, bg = colors.search },
    LineNr = { fg = colors.fg_gutter },
    MatchParen = { fg = colors.fg, bg = colors.match },
    ModeMsg = { fg = colors.green, bold = true },
    MoreMsg = { fg = colors.green, bold = true },
    MsgArea = { fg = colors.fg, bg = bg },
    MsgSeparator = { fg = colors.border, bg = bg },
    NonText = { fg = colors.fg_gutter },
    Normal = { fg = colors.fg, bg = bg },
    NormalFloat = { fg = colors.fg, bg = bg_float },
    NormalNC = { fg = colors.fg, bg = inactive_bg },
    NormalSB = { fg = colors.fg, bg = bg_alt },
    Pmenu = { fg = colors.fg, bg = bg_float },
    PmenuSbar = { bg = bg_alt },
    PmenuSel = { fg = colors.fg, bg = colors.selection },
    PmenuThumb = { bg = colors.border },
    Question = { fg = colors.yellow, bold = true },
    QuickFixLine = { bg = colors.selection_soft },
    Search = { fg = colors.fg, bg = colors.search },
    SignColumn = { fg = colors.fg_gutter, bg = bg },
    SpecialKey = { fg = colors.fg_gutter },
    SpellBad = { sp = colors.red, undercurl = true },
    SpellCap = { sp = colors.blue, undercurl = true },
    SpellLocal = { sp = colors.cyan, undercurl = true },
    SpellRare = { sp = colors.orange, undercurl = true },
    StatusLine = { fg = colors.fg, bg = bg_status },
    StatusLineNC = { fg = colors.comment, bg = bg_status },
    Substitute = { fg = colors.fg, bg = colors.diag_bg.error },
    TabLine = { fg = colors.comment, bg = bg_alt },
    TabLineFill = { bg = bg_alt },
    TabLineSel = { fg = colors.fg, bg = colors.panel_alt },
    Title = { fg = colors.yellow },
    VertSplit = { fg = colors.border, bg = bg },
    Visual = { bg = colors.selection },
    VisualNOS = { bg = colors.selection },
    WarningMsg = { fg = colors.yellow },
    Whitespace = { fg = colors.fg_gutter },
    WildMenu = { fg = colors.fg, bg = colors.selection },
    WinBar = { fg = colors.fg_dark, bg = bg },
    WinBarNC = { fg = colors.comment, bg = bg },
    WinSeparator = { fg = colors.border, bg = bg },
    qfFileName = { fg = colors.blue },
    qfLineNr = { fg = colors.comment },

    Comment = merge({ fg = colors.comment }, styles.comments),
    Constant = { fg = colors.purple },
    String = merge({ fg = colors.green }, styles.strings),
    Character = { fg = colors.green },
    Number = { fg = colors.purple },
    Boolean = { fg = colors.purple },
    Float = { fg = colors.purple },
    Identifier = merge({ fg = colors.fg_soft }, styles.variables),
    Function = merge({ fg = colors.green }, styles.functions),
    Statement = { fg = colors.orange },
    Conditional = { fg = colors.orange },
    Repeat = { fg = colors.orange },
    Label = { fg = colors.fg_soft },
    Operator = { fg = colors.fg_soft },
    Keyword = merge({ fg = colors.orange }, styles.keywords),
    Exception = { fg = colors.orange },
    PreProc = { fg = colors.orange },
    Include = { fg = colors.orange },
    Define = { fg = colors.orange },
    Macro = { fg = colors.purple },
    PreCondit = { fg = colors.orange },
    Type = merge({ fg = colors.yellow }, styles.types),
    StorageClass = { fg = colors.yellow },
    Structure = { fg = colors.yellow },
    Typedef = { fg = colors.yellow },
    Special = { fg = colors.fg_soft },
    SpecialChar = { fg = colors.purple },
    Tag = { fg = colors.blue },
    Delimiter = { fg = colors.fg_dark },
    SpecialComment = { fg = colors.comment },
    Debug = { fg = colors.red },
    Underlined = { underline = true },
    Ignore = { fg = colors.comment },
    Error = { fg = colors.red },
    Todo = { fg = colors.bg, bg = colors.yellow, bold = true },

    ["@annotation"] = { fg = colors.yellow },
    ["@attribute"] = { fg = colors.yellow },
    ["@boolean"] = link("Boolean"),
    ["@character"] = link("Character"),
    ["@character.special"] = { fg = colors.purple },
    ["@comment"] = link("Comment"),
    ["@conditional"] = link("Conditional"),
    ["@constant"] = link("Constant"),
    ["@constant.builtin"] = { fg = colors.purple },
    ["@constant.macro"] = { fg = colors.purple },
    ["@constructor"] = { fg = colors.yellow },
    ["@exception"] = link("Exception"),
    ["@field"] = { fg = colors.fg_soft },
    ["@function"] = link("Function"),
    ["@function.builtin"] = { fg = colors.green },
    ["@function.call"] = link("Function"),
    ["@function.macro"] = { fg = colors.green },
    ["@keyword"] = link("Keyword"),
    ["@keyword.coroutine"] = { fg = colors.orange, italic = true },
    ["@keyword.function"] = { fg = colors.orange, italic = true },
    ["@keyword.operator"] = { fg = colors.orange },
    ["@keyword.return"] = { fg = colors.orange, italic = true },
    ["@label"] = link("Label"),
    ["@markup.heading"] = { fg = colors.purple, bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = colors.blue, underline = true },
    ["@markup.link.label"] = { fg = colors.cyan },
    ["@markup.link.url"] = { fg = colors.green, underline = true },
    ["@markup.list"] = { fg = colors.purple },
    ["@markup.quote"] = { fg = colors.comment, italic = true },
    ["@markup.raw"] = { fg = colors.green },
    ["@markup.strong"] = { bold = true },
    ["@method"] = link("Function"),
    ["@module"] = { fg = colors.fg_dark },
    ["@namespace"] = { fg = colors.fg_dark },
    ["@number"] = link("Number"),
    ["@number.float"] = link("Float"),
    ["@operator"] = link("Operator"),
    ["@parameter"] = { fg = colors.fg },
    ["@property"] = { fg = colors.fg_soft },
    ["@punctuation.bracket"] = { fg = colors.fg_dark },
    ["@punctuation.delimiter"] = { fg = colors.fg_dark },
    ["@punctuation.special"] = { fg = colors.purple },
    ["@string"] = link("String"),
    ["@string.documentation"] = { fg = colors.green, italic = true },
    ["@string.escape"] = { fg = colors.purple },
    ["@string.regexp"] = { fg = colors.cyan },
    ["@string.special"] = { fg = colors.purple },
    ["@tag"] = { fg = colors.purple },
    ["@tag.attribute"] = { fg = colors.yellow },
    ["@tag.delimiter"] = { fg = colors.comment },
    ["@type"] = link("Type"),
    ["@type.builtin"] = { fg = colors.yellow, italic = true },
    ["@type.definition"] = { fg = colors.yellow },
    ["@type.qualifier"] = { fg = colors.purple, italic = true },
    ["@variable"] = link("Identifier"),
    ["@variable.builtin"] = { fg = colors.purple, italic = true },
    ["@variable.member"] = { fg = colors.fg_soft },
    ["@variable.parameter"] = link("@parameter"),
    ["@lsp.mod.defaultLibrary"] = { fg = colors.fg_dark },
    ["@lsp.mod.deprecated"] = { fg = colors.comment, strikethrough = true },
    ["@lsp.type.class"] = link("Type"),
    ["@lsp.type.comment"] = link("Comment"),
    ["@lsp.type.decorator"] = { fg = colors.yellow },
    ["@lsp.type.enum"] = link("Type"),
    ["@lsp.type.enumMember"] = { fg = colors.purple },
    ["@lsp.type.function"] = link("Function"),
    ["@lsp.type.interface"] = link("Type"),
    ["@lsp.type.macro"] = { fg = colors.purple },
    ["@lsp.type.method"] = link("Function"),
    ["@lsp.type.namespace"] = { fg = colors.yellow },
    ["@lsp.type.parameter"] = link("@parameter"),
    ["@lsp.type.property"] = link("@property"),
    ["@lsp.type.struct"] = link("Structure"),
    ["@lsp.type.type"] = link("Type"),
    ["@lsp.type.typeParameter"] = { fg = colors.yellow, italic = true },
    ["@lsp.type.variable"] = link("Identifier"),
    ["@parameter.typescript"] = { fg = colors.fg },
    ["@parameter.tsx"] = { fg = colors.fg },
    ["@property.typescript"] = { fg = colors.fg_soft },
    ["@property.tsx"] = { fg = colors.fg_soft },
    ["@variable.member.typescript"] = { fg = colors.fg_soft },
    ["@variable.member.tsx"] = { fg = colors.fg_soft },
    ["@function.typescript"] = { fg = colors.green },
    ["@function.tsx"] = { fg = colors.green },
    ["@function.method.typescript"] = { fg = colors.green },
    ["@function.method.tsx"] = { fg = colors.green },
    ["@constructor.typescript"] = { fg = colors.yellow },
    ["@constructor.tsx"] = { fg = colors.yellow },
    ["@type.typescript"] = { fg = colors.yellow },
    ["@type.tsx"] = { fg = colors.yellow },
    ["@type.qualifier.typescript"] = { fg = colors.purple, italic = true },
    ["@type.qualifier.tsx"] = { fg = colors.purple, italic = true },
    ["@lsp.type.class.typescript"] = { fg = colors.yellow },
    ["@lsp.type.class.typescriptreact"] = { fg = colors.yellow },
    ["@lsp.type.function.typescript"] = { fg = colors.green },
    ["@lsp.type.function.typescriptreact"] = { fg = colors.green },
    ["@lsp.type.interface.typescript"] = { fg = colors.yellow, italic = true },
    ["@lsp.type.interface.typescriptreact"] = { fg = colors.yellow, italic = true },
    ["@lsp.type.method.typescript"] = { fg = colors.green },
    ["@lsp.type.method.typescriptreact"] = { fg = colors.green },
    ["@lsp.type.parameter.typescript"] = { fg = colors.fg },
    ["@lsp.type.parameter.typescriptreact"] = { fg = colors.fg },
    ["@lsp.type.property.typescript"] = { fg = colors.fg_soft },
    ["@lsp.type.property.typescriptreact"] = { fg = colors.fg_soft },
    ["@lsp.type.typeParameter.typescript"] = { fg = colors.fg_dark, italic = true },
    ["@lsp.type.typeParameter.typescriptreact"] = { fg = colors.fg_dark, italic = true },
    ["@lsp.type.variable.typescript"] = { fg = colors.fg_soft },
    ["@lsp.type.variable.typescriptreact"] = { fg = colors.fg_soft },
    ["@diff.delta"] = { fg = colors.git.change },
    ["@diff.minus"] = { fg = colors.git.delete },
    ["@diff.plus"] = { fg = colors.git.add },

    Added = { fg = colors.git.add },
    Changed = { fg = colors.git.change },
    Removed = { fg = colors.git.delete },
    GitSignsAdd = { fg = colors.git.add },
    GitSignsChange = { fg = colors.git.change },
    GitSignsDelete = { fg = colors.git.delete },
    GitSignsCurrentLineBlame = { fg = colors.comment, italic = true },

    BlinkCmpDoc = { fg = colors.fg, bg = bg_float },
    BlinkCmpDocBorder = { fg = colors.border, bg = bg_float },
    BlinkCmpGhostText = { fg = colors.comment, italic = true },
    BlinkCmpKindClass = { fg = colors.teal },
    BlinkCmpKindColor = { fg = colors.purple },
    BlinkCmpKindConstant = { fg = colors.purple },
    BlinkCmpKindEnum = { fg = colors.teal },
    BlinkCmpKindFunction = { fg = colors.green },
    BlinkCmpKindInterface = { fg = colors.teal },
    BlinkCmpKindKeyword = { fg = colors.orange },
    BlinkCmpKindMethod = { fg = colors.green },
    BlinkCmpKindProperty = { fg = colors.fg_soft },
    BlinkCmpKindSnippet = { fg = colors.green },
    BlinkCmpKindText = { fg = colors.fg },
    BlinkCmpKindVariable = { fg = colors.fg_soft },
    BlinkCmpLabel = { fg = colors.fg },
    BlinkCmpLabelDeprecated = { fg = colors.comment, strikethrough = true },
    BlinkCmpLabelDetail = { fg = colors.comment },
    BlinkCmpLabelMatch = { fg = colors.blue },
    BlinkCmpMenu = { fg = colors.fg, bg = bg_float },
    BlinkCmpMenuBorder = { fg = colors.border, bg = bg_float },
    BlinkCmpSignatureHelp = { fg = colors.fg, bg = bg_float },
    BlinkCmpSignatureHelpBorder = { fg = colors.cyan, bg = bg_float },
    BlinkCmpSource = { fg = colors.comment },

    CmpDocumentation = { fg = colors.fg, bg = bg_float },
    CmpDocumentationBorder = { fg = colors.border, bg = bg_float },
    CmpItemAbbr = { fg = colors.fg },
    CmpItemAbbrDeprecated = { fg = colors.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = colors.blue },
    CmpItemAbbrMatchFuzzy = { fg = colors.cyan },
    CmpItemKindClass = { fg = colors.teal },
    CmpItemKindColor = { fg = colors.purple },
    CmpItemKindConstant = { fg = colors.purple },
    CmpItemKindEnum = { fg = colors.teal },
    CmpItemKindField = { fg = colors.blue },
    CmpItemKindFunction = { fg = colors.green },
    CmpItemKindInterface = { fg = colors.teal },
    CmpItemKindKeyword = { fg = colors.orange },
    CmpItemKindMethod = { fg = colors.green },
    CmpItemKindProperty = { fg = colors.blue },
    CmpItemKindSnippet = { fg = colors.green },
    CmpItemKindText = { fg = colors.fg },
    CmpItemKindVariable = { fg = colors.fg_dark },
    CmpItemMenu = { fg = colors.comment },

    FlashBackdrop = { fg = colors.comment },
    FlashCurrent = { fg = colors.fg, bg = colors.search_current },
    FlashLabel = { fg = colors.fg, bg = colors.diag_bg.error },
    FlashMatch = { fg = colors.fg, bg = colors.search },
    FlashPrompt = { fg = colors.cyan },

    IblIndent = { fg = colors.border },
    IblScope = { fg = colors.blue },
    IndentBlanklineChar = { fg = colors.border },
    IndentBlanklineContextChar = { fg = colors.blue },
    IndentBlanklineContextStart = { sp = colors.blue, underline = true },
    IndentBlanklineSpaceChar = { fg = colors.border },

    LazyButton = { fg = colors.fg, bg = bg_alt },
    LazyButtonActive = { fg = colors.blue, bg = colors.selection_soft },
    LazyComment = { fg = colors.comment },
    LazyCommit = { fg = colors.yellow },
    LazyDir = { fg = colors.blue },
    LazyH1 = { fg = colors.purple, bg = colors.selection_soft, bold = true },
    LazyH2 = { fg = colors.purple },
    LazyLocal = { fg = colors.green },
    LazyNormal = { fg = colors.fg, bg = bg },
    LazyProgressDone = { fg = colors.green },
    LazyProgressTodo = { fg = colors.comment },
    LazyReasonCmd = { fg = colors.purple },
    LazyReasonEvent = { fg = colors.cyan },
    LazyReasonImport = { fg = colors.orange },
    LazyReasonKeys = { fg = colors.yellow },
    LazyReasonPlugin = { fg = colors.blue },
    LazyReasonRuntime = { fg = colors.red },
    LazyReasonSource = { fg = colors.green },
    LazyValue = { fg = colors.comment },

    MasonError = { fg = colors.red },
    MasonHeader = { fg = colors.blue, bg = colors.selection_soft, bold = true },
    MasonHeaderSecondary = { fg = colors.purple, bg = colors.selection_soft, bold = true },
    MasonHighlight = { fg = colors.blue },
    MasonHighlightBlock = { fg = colors.cyan, bg = colors.match, bold = true },
    MasonHighlightBlockBold = { fg = colors.cyan, bg = colors.match, bold = true },
    MasonHighlightSecondary = { fg = colors.purple },
    MasonMuted = { fg = colors.comment },
    MasonMutedBlock = { fg = colors.comment, bg = bg_alt },
    MasonNormal = { fg = colors.fg, bg = bg },

    MiniIndentscopeSymbol = { fg = colors.blue },
    MiniStatuslineDevinfo = { fg = colors.comment, bg = bg_status },
    MiniStatuslineFileinfo = { fg = colors.fg_dark, bg = bg_status },
    MiniStatuslineFilename = { fg = colors.fg, bg = bg_status },
    MiniStatuslineInactive = { fg = colors.comment, bg = bg_status },
    MiniStatuslineModeCommand = { fg = colors.purple, bg = bg_status, bold = true },
    MiniStatuslineModeInsert = { fg = colors.green, bg = bg_status, bold = true },
    MiniStatuslineModeNormal = { fg = colors.blue, bg = bg_status, bold = true },
    MiniStatuslineModeOther = { fg = colors.cyan, bg = bg_status, bold = true },
    MiniStatuslineModeReplace = { fg = colors.red, bg = bg_status, bold = true },
    MiniStatuslineModeVisual = { fg = colors.orange, bg = bg_status, bold = true },

    NeoTreeBufferNumber = { fg = colors.comment },
    NeoTreeCursorLine = { bg = colors.selection },
    NeoTreeDimText = { fg = colors.comment },
    NeoTreeDirectoryIcon = { fg = colors.blue },
    NeoTreeDirectoryName = { fg = colors.fg_soft },
    NeoTreeDotfile = { fg = colors.comment },
    NeoTreeEndOfBuffer = { fg = bg_alt, bg = bg_alt },
    NeoTreeExpander = { fg = colors.fg_gutter },
    NeoTreeFadeText1 = { fg = colors.comment },
    NeoTreeFadeText2 = { fg = colors.fg_gutter },
    NeoTreeFileIcon = { fg = colors.fg_dark },
    NeoTreeFileName = { fg = colors.fg },
    NeoTreeFileNameOpened = { fg = colors.fg_bright, bold = true },
    NeoTreeFileStats = { fg = colors.comment },
    NeoTreeFileStatsHeader = { fg = colors.fg_dark },
    NeoTreeStats = { fg = colors.comment },
    NeoTreeStatsHeader = { fg = colors.fg_dark },
    NeoTreeFilterTerm = { fg = colors.purple, bold = true },
    NeoTreeFloatBorder = { fg = colors.border, bg = bg_float },
    NeoTreeFloatNormal = { fg = colors.fg, bg = bg_float },
    NeoTreeFloatTitle = { fg = colors.fg_bright, bg = bg_float, bold = true },
    NeoTreeGitAdded = { fg = colors.git.add },
    NeoTreeGitConflict = { fg = colors.red, bold = true },
    NeoTreeGitDeleted = { fg = colors.git.delete },
    NeoTreeGitIgnored = { fg = colors.comment },
    NeoTreeGitModified = { fg = colors.git.change },
    NeoTreeGitRenamed = { fg = colors.purple },
    NeoTreeGitStaged = { fg = colors.git.add },
    NeoTreeGitUnstaged = { fg = colors.git.change },
    NeoTreeGitUntracked = { fg = colors.green },
    NeoTreeHiddenByName = { fg = colors.comment },
    NeoTreeIgnored = { fg = colors.comment },
    NeoTreeIndentMarker = { fg = colors.border },
    NeoTreeMessage = { fg = colors.comment, italic = true },
    NeoTreeModified = { fg = colors.yellow },
    NeoTreeNormal = { fg = colors.fg, bg = bg_alt },
    NeoTreeNormalNC = { fg = colors.fg, bg = bg_alt },
    NeoTreePreview = { fg = colors.fg, bg = colors.search },
    NeoTreeRootName = { fg = colors.purple, bold = true },
    NeoTreeSeparator = { fg = colors.border, bg = bg_alt },
    NeoTreeSignColumn = { fg = colors.fg_gutter, bg = bg_alt },
    NeoTreeStatusLine = { fg = colors.comment, bg = bg_status },
    NeoTreeStatusLineNC = { fg = colors.comment, bg = bg_status },
    NeoTreeSymbolicLinkTarget = { fg = colors.cyan, italic = true },
    NeoTreeTabActive = { fg = colors.fg_bright, bg = colors.panel_alt, bold = true },
    NeoTreeTabInactive = { fg = colors.comment, bg = bg_alt },
    NeoTreeTabSeparatorActive = { fg = colors.border_focus, bg = bg_alt },
    NeoTreeTabSeparatorInactive = { fg = colors.border, bg = bg_alt },
    NeoTreeTitleBar = { fg = colors.fg_bright, bg = colors.panel_alt, bold = true },
    NeoTreeVertSplit = { fg = colors.border, bg = bg_alt },
    NeoTreeWinSeparator = { fg = colors.border, bg = bg_alt },
    NeoTreeWindowsHidden = { fg = colors.comment },

    NvimTreeCursorLine = { bg = colors.selection },
    NvimTreeFolderIcon = { fg = colors.blue },
    NvimTreeFolderName = { fg = colors.blue },
    NvimTreeGitDeleted = { fg = colors.git.delete },
    NvimTreeGitDirty = { fg = colors.git.change },
    NvimTreeGitNew = { fg = colors.git.add },
    NvimTreeImageFile = { fg = colors.orange },
    NvimTreeIndentMarker = { fg = colors.border },
    NvimTreeNormal = { fg = colors.fg, bg = bg_alt },
    NvimTreeNormalNC = { fg = colors.fg, bg = bg_alt },
    NvimTreeOpenedFile = { fg = colors.purple },
    NvimTreeRootFolder = { fg = colors.purple },
    NvimTreeSpecialFile = { fg = colors.yellow, underline = true },
    NvimTreeWinSeparator = { fg = colors.border, bg = bg_alt },

    TelescopeBorder = { fg = colors.border, bg = bg_float },
    TelescopeMatching = { fg = colors.yellow },
    TelescopeNormal = { fg = colors.fg, bg = bg_float },
    TelescopePreviewTitle = { fg = colors.green, bg = bg_float, bold = true },
    TelescopePromptBorder = { fg = colors.border_focus, bg = bg_float },
    TelescopePromptNormal = { fg = colors.fg, bg = bg_float },
    TelescopePromptPrefix = { fg = colors.purple },
    TelescopePromptTitle = { fg = colors.blue, bg = bg_float, bold = true },
    TelescopeResultsTitle = { fg = colors.purple, bg = bg_float, bold = true },
    TelescopeSelection = { bg = colors.selection },

    TreesitterContext = { bg = bg_alt },
    TreesitterContextBottom = { sp = colors.border, underline = true },
    TreesitterContextLineNumber = { fg = colors.comment },

    WhichKey = { fg = colors.blue },
    WhichKeyBorder = { fg = colors.border, bg = bg_float },
    WhichKeyDesc = { fg = colors.cyan },
    WhichKeyFloat = { bg = bg_float },
    WhichKeyGroup = { fg = colors.purple },
    WhichKeyIcon = { fg = colors.orange },
    WhichKeySeparator = { fg = colors.comment },
    WhichKeyValue = { fg = colors.comment },
  }
end

return M
